### ISSUE TITLE
wss 也是开启tls就能兼容吗？

### ISSUE THREAD

**Issue by LikeNeko** [ikilobyte/netman#6]

**Comment by ikilobyte** [comment]
目前这块有点问题，不能单独使用，可以在Nginx端开启ssl，然后转发到websocket server

**Comment by LikeNeko** [comment]
是因为啥呢，go的tls库不支持？

**Comment by ikilobyte** [comment]
你是怎么用的

**Comment by LikeNeko** [comment]
准备弄个网关，然后app和web都能走到这边，然后建立长连接，但卡在web里https必须要wss才能连上

**Comment by LikeNeko** [comment]
不行的话我就app和web拆成俩服务器算了

**Comment by ikilobyte** [comment]
websocket不开启tls启动，用nginx转发就可以满足你的需求了

**Comment by LikeNeko** [comment]
这样的话有点担心前面的nginx挂掉

**Comment by ikilobyte** [comment]
nginx不用担心，挂不了

**Comment by LikeNeko** [comment]
行
